language: java
jdk:
- oraclejdk8
services:
- mysql
dist: trusty
sudo: required
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
before_script:
- mysql -u root -e 'CREATE DATABASE labspring;'
- mysql -u root -e "CREATE USER 'sa'@'localhost' IDENTIFIED BY 'sa';"
- mysql -u root -e "GRANT ALL ON labspring.* TO 'sa'@'localhost';"
before_install:
- chmod +x mvnw
deploy:
  provider: heroku
  on:
    all_branches: true
  api_key:
    secure: CvDiq7D3+6JpAlRFtwOFy22aaWgZK6Az1Rl1BhZjnoygB3rfOhAiY8SKZSr2odyowf6IGHNNGiSE77/pTVTty0hTDf9EciEtqV1OdZDdUzOMmJ/7yf+ietA01TJlZmEVBPSfQJZ3uozSfhbobe0ZS46qaTxyxqAO+lr69SD1QtFH2ttfj2djUKgecwZ9+vTk292w3l/9dK4MrWWoJySVBfCxauX5PQOoFEsVG2sTXqL/h2+eiIZRlKVn3BzS/4ytb4ArsaPgcSrV6joQNEPtWL10Z4DSQIe+s00mMc1kyHiKcXcfSN3JVDXOB3yrxXyVFu7nL1C6aGN61tZVKwKP4Q8StIbY/M1kdPGa6JbEkkgEVbBqVbuM9hTsLkjuk8PKEI5hPhdgV2gN28GLSVGmO02SHPJtB/3vzORZOmwvvQrEJj1RELtXVzoy/u48sT6u/2fhsVXiYugZxDYH5ndbRuFmYFCT1UgKN0DMGTbrnEahdT6poZ7o6Ziow5O9vLkBw98H7oi4GzKzROlMajy3kCzwphRBmHzdpUL5oeAtJ+JW3n+wBRy+O4KoXJqKTqiaGT3R/w0zvaMv5HAE/avqwG0Qo8nyVzAGPQC4i6udrRmTqWGDEJZ9JAw4jUZgNRhJC/N/gmgSdCPHdOcOEBmO9bNUJFyHzG2jTFk6fAu3h8w=
